name: Create Package

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Build
      run: |
        pip install build
        python -m build
    - name: Upload artifacts  
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
